name: build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  VERSION: mc1.20.1-0.0.1-beta-fabric
  VERSION_TYPE: beta
  RELEASE_NAME: 0.0.1 (beta) for Fabric 1.20.1
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check JSON
        uses: ocular-d/json-linter@0.0.2

      - name: Zip Data Pack
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: "villagerplusmasontrades-${{env.VERSION}}.zip"
          exclusions: "*.git* ./assets* .gitignore LICENSE README.md"
